### ISSUE TITLE
微信连接失败

### ISSUE THREAD

**Issue by Jarvanh** [546669204/wechatbot-xposed#1]
![image](https://user-images.githubusercontent.com/5900885/44353765-a00f8e80-a4da-11e8-9247-9298e71be4bd.png)

**Comment by 546669204** [comment]
端口号需要换成188 
1778是后台端口
微信版本需要使用6.6.6

**Comment by Jarvanh** [comment]
微信为releases页面下载的6.6.6版本
端口换成了188，还是显示微信连接失败

wehook会不定期停止运行

**Comment by 546669204** [comment]
有给root权限吗 可以调日志出来看看是什么错误 因为wehookGG了所以就不会连接微信

**Comment by Jarvanh** [comment]
有给root权限
日志怎么查看呢

**Comment by 546669204** [comment]
adb logcat

**Comment by Jarvanh** [comment]
08-21 23:18:07.107 10170-10207/com.example.administrator.webot E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.administrator.webot, PID: 10170
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libutils.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
        at java.lang.System.loadLibrary(System.java:1562)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:174)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)
        at com.example.administrator.webot.openSQLite.openWxDb(openSQLite.java:226)
        at com.example.administrator.webot.openSQLite.getRContentJson(openSQLite.java:59)
        at com.example.administrator.webot.MySocket.main(MySocket.java:267)
        at com.example.administrator.webot.MyService$1.run(MyService.java:28)
        at java.lang.Thread.run(Thread.java:761)

**Comment by 546669204** [comment]
环境问题明天修复一下

**Comment by Jarvanh** [comment]
好的，谢谢

**Comment by 546669204** [comment]
hello 有时间吗 可以试一下 这个安装包 我修改了目标版本 [debug.apk](https://files.catbox.moe/dq0xih.apk)

**Comment by Jarvanh** [comment]
![image](https://user-images.githubusercontent.com/5900885/44528803-fff57780-a71c-11e8-836d-dec49106f0d9.png)

卸载了重新安装，安装不了。

**Comment by Jarvanh** [comment]
貌似是这里的问题

![image](https://user-images.githubusercontent.com/5900885/44546132-993a8300-a749-11e8-92e0-b43cc262bf22.png)

**Comment by 546669204** [comment]
@Jarvanh 这个错误是拿不到微信的数据库。
之前的那个版本安装不了吗？
这边你高版本的系统 被限制了获取系统目录文件的权限
我那个版本修改了目标版本 按理说是可以的。

**Comment by Jarvanh** [comment]
你那个安装包不能安装，我clone下来修改为 targetSdkVersion 23，能安装，但是一样会崩溃。

08-24 12:05:16.599 11303-11321/com.example.administrator.webot E/Database: CREATE TABLE android_metadata failed
08-24 12:05:16.600 11303-11321/com.example.administrator.webot E/Database: Failed to setLocale() when constructing, closing the database
    net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: create locale table failed
        at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
        at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2474)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2338)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1087)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1028)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1002)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1128)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1121)
        at com.example.administrator.webot.openSQLite.openWxDb(openSQLite.java:236)
        at com.example.administrator.webot.openSQLite.getRContentJson(openSQLite.java:59)
        at com.example.administrator.webot.MySocket.rebotSocket(MySocket.java:335)
        at com.example.administrator.webot.MySocket.receiveMsg(MySocket.java:380)
        at com.example.administrator.webot.MySocket.main(MySocket.java:317)
        at com.example.administrator.webot.MyService$1.run(MyService.java:20)
        at java.lang.Thread.run(Thread.java:761)

![image](https://user-images.githubusercontent.com/5900885/44564705-09232a80-a797-11e8-8b97-6b430b1451b1.png)

**Comment by 546669204** [comment]
@Jarvanh  你这边微信有启动 并且登录吗 让微信自己先产生数据库。

**Comment by Jarvanh** [comment]
有，我还尝试发了一些信息

**Comment by Jarvanh** [comment]
要不开个TeamViewer 你远程调试一下？

**Comment by 546669204** [comment]
晚上有时间吗。晚上可以调试下。

**Comment by Jarvanh** [comment]
晚上8-11点ok吗？

到时候邮件联系我吧
jarvanh18@gmail.com

**Comment by 546669204** [comment]
好。

**Comment by jpfree** [comment]
我这边也是同样的问题，请问如何解决啊

**Comment by 546669204** [comment]
@jpfree 试试这个版本的 [apk](https://files.catbox.moe/zgpzgi.apk)
